# Generated by Django 4.1.1 on 2022-09-09 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f010db8e-d62a-4ad0-936c-f59f8d988203'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
