# Generated by Django 4.1.1 on 2022-09-09 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b24092c4-53b5-49cf-9d7d-809ac7638663'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
