# Generated by Django 4.1.1 on 2022-09-09 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ae6fbc73-e7c6-45d8-ba89-52c6d7479bc7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
