# Generated by Django 4.1.1 on 2022-09-09 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3f82c05c-0643-4b98-9a49-3aba67680d84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
