# Generated by Django 4.1.1 on 2022-09-17 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f332e671-65af-44db-8f34-b2d7b2ccd36c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
